version: '3.0'

services:
  app:
    image: registry.digitalocean.com/web-enterprise/web-enterprise-frontend:latest
    container_name: web-enterprise-frontend
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    restart: "always"
    